# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'

target 'Credit Score' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Credit Score
    pod 'CreditScoreUISDK'
    
  target 'Credit ScoreTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'OHHTTPStubs', '8.0.0'
    pod 'OHHTTPStubs/Swift', '8.0.0'
  end

end
